### ISSUE TITLE
Cannot call function from within the string interpolator

### ISSUE THREAD

**Issue by chenweiyj** [mattroberts297/slf4s#1]
When I call 

``` scala
log.info(s"$xxx($args)")
```

it got an error in compile. So how can I call a method in the log string?

**Comment by chenweiyj** [comment]
I think I might solve it. Just replace the string as follows

``` scala
log.info(s"${xxx(args)}")
```

**Comment by mattroberts297** [comment]
Sorry for the delay. Your solution is correct. Here is the complete [string interpolation reference](http://docs.scala-lang.org/overviews/core/string-interpolation.html). Also, your solution allows arbitrary expressions (not just function calls), for example:

``` scala
log.info(s"1 + 1 = ${1 + 1}")
```

I've updated the README.md with examples. I'll close for now but feel free to open again.

Thanks,
Matt.
