### ISSUE TITLE
Make Logger Serializable

### ISSUE THREAD

**Issue by NoOrdInaryGuy** [mattroberts297/slf4s#15]
As of SLF4J version 1.5.3, SLF4J Logger instances survive serialization - which is especially useful when using tools like Apache Spark.

Please can Logger in slf4s also be made serializable in the next release?

**Comment by mattroberts297** [comment]
@NoOrdInaryGuy and I discussed this offline and decided it was undesirable because a logger that is valid on one machine might not be valid on another. Instead, we recommend people do not serialise their loggers.
