### ISSUE TITLE
Publish Scaladoc

### ISSUE THREAD

**Issue by ngocdaothanh** [mattroberts297/slf4s#3]
Plase publish Scaladoc (to GitHub Pages?).

**Comment by mattroberts297** [comment]
This is a good point. Whilst the library is very small, there are methods that I have not mentioned in the Usage section of the README.

**Comment by mattroberts297** [comment]
This is now published at http://slf4s.org/api/1.7.7/

**Comment by ngocdaothanh** [comment]
Thanks!
I plan to use your lib in [Xitrum](http://xitrum-framework.github.io/xitrum/).

**Comment by ngocdaothanh** [comment]
Thanks for your lib.
[Xitrum](http://xitrum-framework.github.io/xitrum/) now uses SLF4S:
https://github.com/xitrum-framework/xitrum/blob/master/build.sbt#L41

**Comment by ngocdaothanh** [comment]
FYI, SLF4S is mentioned in Xitrum Guide here:
http://xitrum-framework.github.io/xitrum/guide/deps.html#dependency-libraries
http://xitrum-framework.github.io/xitrum/guide/howto.html#don-t-have-to-check-log-level-before-logging
