### ISSUE TITLE
Publish for scala 2.9.x

### ISSUE THREAD

**Issue by momania** [mattroberts297/slf4s#5]
Can you possibly also publish the 2.9.x version? Currently only the 2.10.x and 2.11.x versions are available on Sonatype.

**Comment by mattroberts297** [comment]
No problem. I've just released version 1.7.10 for 2.9.x, 2.10 and 2.11 for you. It'll take a little while to hit maven central. Let's leave this open till it's visible.

**Comment by momania** [comment]
Great, thanks a lot!

**Comment by mattroberts297** [comment]
Just checked and [it is visible now](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.slf4s%22). Any problems, let me know.
